version: '3.7'
services:
  db:
    image: postgres:13.1
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: desk_app
    command: bash -c "/fastapi_app/docker/app.sh"
    ports:
      - 9999:8000
    depends_on:
      - db
